2025-04-24 23:48:12,332 - INFO - Refreshing proxy list...
2025-04-24 23:48:12,332 - INFO - Using local file for user agents: /opt/anaconda3/lib/python3.12/site-packages/http_request_randomizer/requests/proxy/../data/user_agents.txt
2025-04-24 23:48:12,333 - DEBUG - === Initialized Proxy Parsers ===
2025-04-24 23:48:12,333 - DEBUG - 	 FreeProxy parser of 'http://free-proxy-list.net' with required bandwidth: '150' KBs
2025-04-24 23:48:12,333 - DEBUG - 	 PremProxy parser of 'https://premproxy.com/list/' with required bandwidth: '150' KBs
2025-04-24 23:48:12,333 - DEBUG - 	 SslProxy parser of 'https://www.sslproxies.org' with required bandwidth: '150' KBs
2025-04-24 23:48:12,333 - DEBUG - =================================
2025-04-24 23:48:13,353 - ERROR - Provider FreeProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2025-04-24 23:48:13,355 - DEBUG - Added 0 proxies from FreeProxy
2025-04-24 23:48:15,854 - ERROR - Provider PremProxy failed with Unknown error: HTTPSConnectionPool(host='premproxy.com', port=443): Max retries exceeded with url: /list/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107000e30>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-04-24 23:48:15,855 - DEBUG - Added 0 proxies from PremProxy
2025-04-24 23:48:16,119 - ERROR - Provider SslProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2025-04-24 23:48:16,120 - DEBUG - Added 0 proxies from SslProxy
2025-04-24 23:48:16,121 - DEBUG - Total proxies = 0
2025-04-24 23:48:16,121 - DEBUG - Filtered proxies = 0
2025-04-24 23:48:16,121 - ERROR - Error refreshing proxies: list is empty
2025-04-24 23:48:16,159 - INFO - Starting crawl from page 1 with max_pages=3, max_attractions=None
2025-04-24 23:48:16,159 - INFO - Crawling page 1
2025-04-24 23:48:16,159 - INFO - Fetching URL: https://www.tripadvisor.com/Attractions-g293924-Activities-oa0-Hanoi.html?_=1745513296 (Attempt 1/5)
2025-04-24 23:48:16,159 - INFO - Refreshing proxy list...
2025-04-24 23:48:16,159 - INFO - Using local file for user agents: /opt/anaconda3/lib/python3.12/site-packages/http_request_randomizer/requests/proxy/../data/user_agents.txt
2025-04-24 23:48:16,159 - DEBUG - === Initialized Proxy Parsers ===
2025-04-24 23:48:16,159 - DEBUG - 	 FreeProxy parser of 'http://free-proxy-list.net' with required bandwidth: '150' KBs
2025-04-24 23:48:16,159 - DEBUG - 	 PremProxy parser of 'https://premproxy.com/list/' with required bandwidth: '150' KBs
2025-04-24 23:48:16,159 - DEBUG - 	 SslProxy parser of 'https://www.sslproxies.org' with required bandwidth: '150' KBs
2025-04-24 23:48:16,159 - DEBUG - =================================
2025-04-24 23:48:16,368 - ERROR - Provider FreeProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2025-04-24 23:48:16,369 - DEBUG - Added 0 proxies from FreeProxy
2025-04-24 23:48:18,833 - ERROR - Provider PremProxy failed with Unknown error: HTTPSConnectionPool(host='premproxy.com', port=443): Max retries exceeded with url: /list/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10775dfa0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-04-24 23:48:18,833 - DEBUG - Added 0 proxies from PremProxy
2025-04-24 23:48:19,027 - ERROR - Provider SslProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2025-04-24 23:48:19,028 - DEBUG - Added 0 proxies from SslProxy
2025-04-24 23:48:19,028 - DEBUG - Total proxies = 0
2025-04-24 23:48:19,028 - DEBUG - Filtered proxies = 0
2025-04-24 23:48:19,028 - ERROR - Error refreshing proxies: list is empty
2025-04-24 23:48:19,416 - ERROR - Request error: 403 Client Error: Forbidden for url: https://www.tripadvisor.com/Attractions-g293924-Activities-oa0-Hanoi.html?_=1745513296
2025-04-24 23:48:19,416 - INFO - Retrying after 68.08 seconds...
